baseURL = "http://example.org/"
languageCode = "en-us"
title = "premi.st"
theme = "premi.st"

DefaultContentLanguage = "en"

[permalinks]
  project = "/projects/:title/"
  talk = "/talks/:title/"

[params]
  author = "Minku Lee"
  public_email = "public@premi.st"
  pgp_public_key = "448C E46C A714 48F8 7788 E57C F530 9452 F2EF 9CEB"

  # mastodon_handle = "premist"
  # mastodon_instance = "noon.social"
  twitter = "premist"
  instagram = "premist"
  facebook = "premist.lee"
  keybase = "premist"
  github = "premist"

  hero1 = "I design,"
  hero2 = "develop,"
  hero3_1 = "and operate"
  hero3_2 = "things."


[languages]
  [languages.en]
    languageName = "English"
  [languages.ko]
    languageName = "한국어"
